import fs from "node:fs";
import { assertPublicSnapshot } from "./public-snapshot.js";
const payload = JSON.parse(fs.readFileSync("promos.json", "utf8"));
const history = JSON.parse(fs.readFileSync("history.json", "utf8"));
assertPublicSnapshot(payload, history);
const files = ["index.html", "promos.json", "history.json", "deal-intelligence.js", "manual-state.js", "offer-time.js"];
fs.rmSync("dist", { recursive: true, force: true });
fs.mkdirSync("dist");
for (const file of files) fs.copyFileSync(file, "dist/" + file);
fs.writeFileSync("dist/.nojekyll", "");
console.log("Built validated public site: " + files.length + " application files.");
